name: 'Cost Management Historical Pricing Script'

on:
  schedule:
    - cron:  '0 6 1 * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      directory: '${{ github.workspace }}'
      solutionDirectory: '/Solutions/CostManagement'
      informationPreference: 'SilentlyContinue'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          ref: main
          token: ${{secrets.MICROSOFTSENTINELCOMMIT}}
        
      - name: BuildScript
        run: |
            .\Solutions\CostManagement\Script\GetMicrosoftSentinelRetailPrices.ps1
        env:
          PAT: ${{secrets.MICROSOFTSENTINELCOMMIT}}
        
      - name: Auto-Commit
        uses: EndBug/add-and-commit@v9
        env:
          PAT: ${{secrets.MICROSOFTSENTINELCOMMIT}}
